language: go
sudo: false
notifications:
  email: false

env:
  global:
    - GO111MODULE=on
    - GOFLAGS="-mod=readonly"

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

git:
  depth: 3
go:
  - 1.15.0
  - tip

before_install:
  - go get -t -v ./...

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)